download_url:
  vcf: https://storage.googleapis.com/gcp-public-data--gnomad/release/{version}/vcf/genomes/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz
  tbi: https://storage.googleapis.com/gcp-public-data--gnomad/release/{version}/vcf/genomes/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz.tbi

chroms:
  # - 1
  # - 2
  # - 3
  # - 4
  # - 5
  # - 6
  # - 7
  # - 8
  # - 9
  # - 10
  # - 11
  # - 12
  # - 13
  # - 14
  # - 15
  # - 16
  - 17
  # - 18
  # - 19
  # - 20
  # - 21  
  # - 22
  # - X
  # - Y

version:
  - 2.1.1
  # - 3.1.2

vcf: data/resources/{version}/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz
vcf_tbi: data/resources/{version}/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz.tbi
gnomad_db: data/results/gnomad_rocksdb_{version}/
gnomad_db_backup: data/results/backups/gnomad_rocksdb_{version}


# too large batch_size may cause memory error
batch_size: 10000

#  17      305     C       T
