download_url:
  '4.1':
    vcf: https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/vcf/genomes/gnomad.genomes.v4.1.sites.{chrom}.vcf.bgz
    tbi: https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/vcf/genomes/gnomad.genomes.v4.1.sites.{chrom}.vcf.bgz.tbi

    
chroms:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21  
  - chr22
  - chrX
  - chrY

version:
  - '4.1'

vcf: data/resources/{version}/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz
vcf_tbi: data/resources/{version}/gnomad.genomes.r{version}.sites.{chrom}.vcf.bgz.tbi
gnomad_db: data/results/gnomad_rocksdb_{version}/
gnomad_db_backup: data/results/backups/gnomad_rocksdb_{version}

# too large batch_size may cause memory error
batch_size: 10000
